#!/bin/bash

# chmod +x /root/jfrog/JFTD-110-GitHub_Actions_for_JFrog/scripts/lab0_configure_npm_virtual_repository/ide-client/solve.sh
/root/swampup25/JFTD-110-GitHub_Actions_for_JFrog/scripts/lab0_configure_npm_virtual_repository/ide-client/solve.sh